import { Args,Field,InputType,Int,Mutation,ObjectType,Query,Resolver } from '@nestjs/graphql';import { UseGuards } from '@nestjs/common';import { PrismaService } from '../prisma.service';import { MailService } from '../mail.service';import { GqlAuthGuard } from '../auth/auth.guard';
@ObjectType()class Settings{@Field(()=>Int)id!:number;@Field()phone!:string;@Field({nullable:true})secondaryPhone?:string;@Field()email!:string;@Field()location!:string;@Field({nullable:true})facebook?:string;@Field({nullable:true})instagram?:string;@Field({nullable:true})x?:string;@Field({nullable:true})linkedin?:string;@Field({nullable:true})youtube?:string;@Field({nullable:true})whatsapp?:string}
@ObjectType()class Message{@Field()id!:string;@Field()name!:string;@Field({nullable:true})email?:string;@Field({nullable:true})phone?:string;@Field({nullable:true})subject?:string;@Field()message!:string;@Field()status!:string;@Field(()=>Date) createdAt!:Date;@Field(()=>Date) updatedAt!:Date}
@ObjectType()class Subscriber{@Field()id!:string;@Field()email!:string;@Field()status!:string;@Field(()=>Date) createdAt!:Date;@Field(()=>Date) updatedAt!:Date}
@ObjectType()class Volunteer{@Field()id!:string;@Field()name!:string;@Field({nullable:true})email?:string;@Field()phone!:string;@Field()interest!:string;@Field({nullable:true})availability?:string;@Field({nullable:true})message?:string;@Field()status!:string;@Field(()=>Date) createdAt!:Date;@Field(()=>Date) updatedAt!:Date}
@ObjectType()class Sponsor{@Field()id!:string;@Field()fullName!:string;@Field({nullable:true})email?:string;@Field()phone!:string;@Field({nullable:true})country?:string;@Field({nullable:true})city?:string;@Field({nullable:true})preferredContact?:string;@Field({nullable:true})sponsorshipPreference?:string;@Field({nullable:true})message?:string;@Field()consent!:boolean;@Field()status!:string;@Field(()=>Date) createdAt!:Date;@Field(()=>Date) updatedAt!:Date}
@ObjectType()class Gallery{@Field()id!:string;@Field()title!:string;@Field()imageUrl!:string;@Field({nullable:true})description?:string;@Field({nullable:true})category?:string;@Field()published!:boolean;@Field(()=>Date) createdAt!:Date;@Field(()=>Date) updatedAt!:Date}
@ObjectType()class News{@Field()id!:string;@Field()title!:string;@Field()slug!:string;@Field()category!:string;@Field({nullable:true})excerpt?:string;@Field()body!:string;@Field({nullable:true})imageUrl?:string;@Field()published!:boolean;@Field(()=>Date,{nullable:true})publishedAt?:Date;@Field(()=>Date) createdAt!:Date;@Field(()=>Date) updatedAt!:Date}
@ObjectType()class DonationMethod{@Field()id!:string;@Field()key!:string;@Field()name!:string;@Field()eyebrow!:string;@Field()detailsJson!:string;@Field()note!:string;@Field(()=>Date)updatedAt!:Date}
@ObjectType()class SiteStatistic{@Field()key!:string;@Field()label!:string;@Field(()=>Int)value!:number;@Field()suffix!:string;@Field(()=>Date)updatedAt!:Date}
@InputType()class DonationMethodInput{@Field()name!:string;@Field()eyebrow!:string;@Field()detailsJson!:string;@Field()note!:string}
@InputType()class SiteStatisticInput{@Field()label!:string;@Field(()=>Int)value!:number;@Field()suffix!:string}
@ObjectType()class Stats{@Field(()=>Int)messages!:number;@Field(()=>Int)newMessages!:number;@Field(()=>Int)newsletter!:number;@Field(()=>Int)pendingNewsletter!:number;@Field(()=>Int)volunteers!:number;@Field(()=>Int)pendingVolunteers!:number;@Field(()=>Int)sponsors!:number;@Field(()=>Int)pendingSponsors!:number;@Field(()=>Int)gallery!:number;@Field(()=>Int)news!:number}
@InputType()class SettingsInput{@Field()phone!:string;@Field({nullable:true})secondaryPhone?:string;@Field()email!:string;@Field()location!:string;@Field({nullable:true})facebook?:string;@Field({nullable:true})instagram?:string;@Field({nullable:true})x?:string;@Field({nullable:true})linkedin?:string;@Field({nullable:true})youtube?:string;@Field({nullable:true})whatsapp?:string}
@InputType()class ContactInput{@Field()name!:string;@Field({nullable:true})email?:string;@Field({nullable:true})phone?:string;@Field({nullable:true})subject?:string;@Field()message!:string}
@InputType()class VolunteerInput{@Field()name!:string;@Field({nullable:true})email?:string;@Field()phone!:string;@Field()interest!:string;@Field({nullable:true})availability?:string;@Field({nullable:true})message?:string}
@InputType()class SponsorInput{@Field()fullName!:string;@Field({nullable:true})email?:string;@Field()phone!:string;@Field({nullable:true})country?:string;@Field({nullable:true})city?:string;@Field({nullable:true})preferredContact?:string;@Field({nullable:true})sponsorshipPreference?:string;@Field({nullable:true})message?:string;@Field()consent!:boolean}
@InputType()class GalleryInput{@Field()title!:string;@Field()imageUrl!:string;@Field({nullable:true})description?:string;@Field({nullable:true})category?:string;@Field({defaultValue:true})published!:boolean}
@InputType()class NewsInput{@Field()title!:string;@Field()slug!:string;@Field()category!:string;@Field({nullable:true})excerpt?:string;@Field()body!:string;@Field({nullable:true})imageUrl?:string;@Field({defaultValue:false})published!:boolean}
const GITHUB_IMAGE_BASE=`https://raw.githubusercontent.com/${process.env.GITHUB_OWNER||"ssemuyabadev"}/${process.env.GITHUB_REPO||"sf_frontend"}/${process.env.GITHUB_BRANCH||"main"}/`;
function normalizeImageUrl(value?:string|null){if(!value)return value??undefined;if(value.startsWith("/images/"))return GITHUB_IMAGE_BASE+value.slice(1);return value;}
@Resolver()export class ContentResolver{constructor(private prisma:PrismaService,private mail:MailService){}
@Query(()=>Settings)siteSettings(){return this.prisma.siteSettings.findUniqueOrThrow({where:{id:1}})}
@Query(()=>[Gallery])async gallery(@Args('publishedOnly',{nullable:true,defaultValue:true})publishedOnly:boolean){const items=await this.prisma.galleryItem.findMany({where:publishedOnly?{published:true}:undefined,orderBy:{createdAt:'desc'}});return items.map(item=>({...item,imageUrl:normalizeImageUrl(item.imageUrl)}));}
@Query(()=>[News])async news(@Args('publishedOnly',{nullable:true,defaultValue:true})publishedOnly:boolean){const items=await this.prisma.newsPost.findMany({where:publishedOnly?{published:true}:undefined,orderBy:{createdAt:'desc'}});return items.map(item=>({...item,imageUrl:normalizeImageUrl(item.imageUrl)}));}
@Query(()=>News,{nullable:true})async newsBySlug(@Args('slug')slug:string){const item=await this.prisma.newsPost.findUnique({where:{slug}});return item?{...item,imageUrl:normalizeImageUrl(item.imageUrl)}:null}
@Query(()=>[DonationMethod])donationMethods(){return this.prisma.donationMethod.findMany({orderBy:{id:'asc'}})}
@Query(()=>[SiteStatistic])statistics(){return this.prisma.siteStatistic.findMany({orderBy:{key:'asc'}})}
@Mutation(()=>Message)async submitContact(@Args('input')input:ContactInput){const name=String(input?.name??'').trim();const email=String(input?.email??'').trim().toLowerCase()||undefined;const phone=String(input?.phone??'').trim()||undefined;const subject=String(input?.subject??'').trim()||undefined;const message=String(input?.message??'').trim();if(!name)throw new Error('Name is required.');if(!message)throw new Error('Message is required.');const saved=await this.prisma.contactMessage.create({data:{name,email,phone,subject,message}});const staffHtml='<h2>New contact enquiry</h2><p><b>'+input.name+'</b>'+(email?' ('+email+')':'')+'</p><p><b>Subject:</b> '+(input.subject||'General enquiry')+'</p><p>'+input.message+'</p>'+(input.phone?'<p><b>Phone:</b> '+input.phone+'</p>':'');const visitorHtml='<div style="font-family:Arial,sans-serif;line-height:1.6"><h2>Thank you for contacting Ssemuyaba Foundation</h2><p>Dear '+input.name+',</p><p>We have received your message and our team will review it shortly. We’ll get back to you as soon as possible.</p><p><b>Your subject:</b> '+(input.subject||'General enquiry')+'</p><p>With gratitude,<br><strong>Ssemuyaba Foundation</strong></p></div>';try{await Promise.all([this.mail.notify('New contact message from '+name,staffHtml),email?this.mail.send(email,'We received your message — Ssemuyaba Foundation',visitorHtml):Promise.resolve()])}catch(error){console.error('Contact email notification failed:',error)}return saved}
@Mutation(()=>Subscriber)async subscribeNewsletter(@Args('email')email:string){const normalized=email.trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(normalized))throw new Error('Please enter a valid email address.');const saved=await this.prisma.newsletterSubscriber.upsert({where:{email:normalized},update:{status:'NEW'},create:{email:normalized}});await Promise.all([this.mail.send(normalized,'Welcome to the Ssemuyaba Foundation newsletter','<div style="font-family:Arial,sans-serif;line-height:1.6"><h2>Thank you for subscribing!</h2><p>We’re glad to have you with us. You’ll receive stories, updates and opportunities to make a difference through the Ssemuyaba Foundation.</p><p>With gratitude,<br><strong>Ssemuyaba Foundation</strong></p></div>'),this.mail.notify('New newsletter subscriber: '+normalized,'<h2>New newsletter subscription</h2><p><b>'+normalized+'</b> subscribed to the foundation newsletter and is awaiting review in the admin dashboard.</p>')]);return saved}
@Mutation(()=>Volunteer)async submitVolunteer(@Args('input')input:VolunteerInput){const name=String(input?.name??'').trim();const email=String(input?.email??'').trim().toLowerCase()||undefined;const phone=String(input?.phone??'').trim();const interest=String(input?.interest??'').trim();const availability=String(input?.availability??'').trim()||undefined;const message=String(input?.message??'').trim()||undefined;if(!name)throw new Error('Name is required.');if(!phone)throw new Error('Phone number is required.');if(!interest)throw new Error('Volunteer interest is required.');const saved=await this.prisma.volunteerApplication.create({data:{name,email,phone,interest,availability,message}});const staffHtml='<h2>New volunteer application</h2><p><b>'+name+'</b>'+(email?' ('+email+')':'')+'</p><p><b>Phone:</b> '+phone+'</p><p><b>Interest:</b> '+interest+'</p><p><b>Availability:</b> '+(availability||'Not specified')+'</p><p><b>Message:</b> '+(message||'No message provided')+'</p>';const visitorHtml='<div style="font-family:Arial,sans-serif;line-height:1.6"><h2>Thank you for volunteering with Ssemuyaba Foundation</h2><p>Dear '+name+',</p><p>Thank you for expressing your interest in volunteering with Ssemuyaba Foundation. We have received your application and our team will review it and contact you about the next steps.</p><p><b>Your area of interest:</b> '+interest+'</p><p>With gratitude,<br><strong>Ssemuyaba Foundation</strong></p></div>';try{await Promise.all([this.mail.notify('New volunteer application from '+name,staffHtml),email?this.mail.send(email,'We received your volunteer application — Ssemuyaba Foundation',visitorHtml):Promise.resolve()])}catch(error){console.error('Volunteer application email notification failed:',error)}return saved}
@Mutation(()=>Sponsor)async submitSponsor(@Args('input')input:SponsorInput){const fullName=String(input?.fullName??'').trim();const email=String(input?.email??'').trim().toLowerCase()||undefined;const phone=String(input?.phone??'').trim();const country=String(input?.country??'').trim()||undefined;const city=String(input?.city??'').trim()||undefined;const preferredContact=String(input?.preferredContact??'').trim()||undefined;const sponsorshipPreference=String(input?.sponsorshipPreference??'').trim()||undefined;const message=String(input?.message??'').trim()||undefined;const consent=input?.consent===true;if(!fullName)throw new Error('Full name is required.');if(!phone)throw new Error('Phone number is required.');if(!consent)throw new Error('Consent is required.');const saved=await this.prisma.sponsorEnquiry.create({data:{fullName,email:email||"",phone,country,city,preferredContact,sponsorshipPreference,message,consent:true}});const staffHtml='<h2>New child sponsorship enquiry</h2><p><b>'+fullName+'</b>'+(email?' ('+email+')':'')+'</p><p><b>Phone:</b> '+phone+'</p><p><b>Location:</b> '+[city,country].filter(Boolean).join(', ')+'</p><p><b>Preferred contact:</b> '+(preferredContact||'Not specified')+'</p><p><b>Sponsorship preference:</b> '+(sponsorshipPreference||'Discuss')+'</p><p><b>Message:</b> '+(message||'No message provided')+'</p>';const visitorHtml='<div style="font-family:Arial,sans-serif;line-height:1.6"><h2>Thank you for your sponsorship enquiry</h2><p>Dear '+fullName+',</p><p>Thank you for your interest in sponsoring a child through Ssemuyaba Foundation. We have received your enquiry and our team will contact you to explain the next steps.</p><p><b>Your preference:</b> '+(sponsorshipPreference||'To discuss')+'</p><p>With gratitude,<br><strong>Ssemuyaba Foundation</strong></p></div>';try{await Promise.all([this.mail.notify('New child sponsorship enquiry from '+fullName,staffHtml),email?this.mail.send(email,'We received your sponsorship enquiry — Ssemuyaba Foundation',visitorHtml):Promise.resolve()])}catch(error){console.error('Sponsor enquiry email notification failed:',error)}return saved}
@Query(()=>Stats)@UseGuards(GqlAuthGuard)async dashboardStats(){const [messages,newMessages,newsletter,pendingNewsletter,volunteers,pendingVolunteers,sponsors,pendingSponsors,gallery,news]=await Promise.all([this.prisma.contactMessage.count(),this.prisma.contactMessage.count({where:{status:'NEW'}}),this.prisma.newsletterSubscriber.count(),this.prisma.newsletterSubscriber.count({where:{status:'NEW'}}),this.prisma.volunteerApplication.count(),this.prisma.volunteerApplication.count({where:{status:'NEW'}}),this.prisma.sponsorEnquiry.count(),this.prisma.sponsorEnquiry.count({where:{status:'NEW'}}),this.prisma.galleryItem.count(),this.prisma.newsPost.count({where:{published:true}})]);return{messages,newMessages,newsletter,pendingNewsletter,volunteers,pendingVolunteers,sponsors,pendingSponsors,gallery,news}}
@Query(()=>[Message])@UseGuards(GqlAuthGuard)contactMessages(){return this.prisma.contactMessage.findMany({orderBy:{createdAt:'desc'}})}
@Query(()=>[Subscriber])@UseGuards(GqlAuthGuard)newsletterSubscribers(){return this.prisma.newsletterSubscriber.findMany({orderBy:{createdAt:'desc'}})}
@Mutation(()=>Subscriber)@UseGuards(GqlAuthGuard)updateNewsletterStatus(@Args('id')id:string,@Args('status')status:string){if(!['NEW','APPROVED','DECLINED'].includes(status))throw new Error('Invalid newsletter status.');return this.prisma.newsletterSubscriber.update({where:{id},data:{status:status as any}})}
@Query(()=>[Volunteer])@UseGuards(GqlAuthGuard)volunteerApplications(){return this.prisma.volunteerApplication.findMany({orderBy:{createdAt:'desc'}})}
@Query(()=>[Sponsor])@UseGuards(GqlAuthGuard)sponsorEnquiries(){return this.prisma.sponsorEnquiry.findMany({orderBy:{createdAt:'desc'}})}
@Mutation(()=>Sponsor)@UseGuards(GqlAuthGuard)updateSponsorStatus(@Args('id')id:string,@Args('status')status:string){if(!['NEW','REPLIED','ARCHIVED'].includes(status))throw new Error('Invalid sponsor status.');return this.prisma.sponsorEnquiry.update({where:{id},data:{status:status as any}})}
@Query(()=>[DonationMethod])@UseGuards(GqlAuthGuard)adminDonationMethods(){return this.prisma.donationMethod.findMany({orderBy:{id:'asc'}})}
@Query(()=>[SiteStatistic])@UseGuards(GqlAuthGuard)adminStatistics(){return this.prisma.siteStatistic.findMany({orderBy:{key:'asc'}})}
@Query(()=>[Gallery])@UseGuards(GqlAuthGuard)async adminGallery(){const items=await this.prisma.galleryItem.findMany({orderBy:{createdAt:'desc'}});return items.map(item=>({...item,imageUrl:normalizeImageUrl(item.imageUrl)}));}
@Query(()=>[News])@UseGuards(GqlAuthGuard)async adminNews(){const items=await this.prisma.newsPost.findMany({orderBy:{createdAt:'desc'}});return items.map(item=>({...item,imageUrl:normalizeImageUrl(item.imageUrl)}));}
@Mutation(()=>Settings)@UseGuards(GqlAuthGuard)async updateSiteSettings(@Args('input')input:SettingsInput){const current=await this.prisma.siteSettings.findUnique({where:{id:1}});const data={phone:String(input.phone??current?.phone??'').trim(),secondaryPhone:input.secondaryPhone===undefined?(current?.secondaryPhone??null):(String(input.secondaryPhone??'').trim()||null),email:String(input.email??current?.email??'').trim(),location:String(input.location??current?.location??'').trim(),facebook:input.facebook===undefined?(current?.facebook??null):(String(input.facebook??'').trim()||null),instagram:input.instagram===undefined?(current?.instagram??null):(String(input.instagram??'').trim()||null),x:input.x===undefined?(current?.x??null):(String(input.x??'').trim()||null),linkedin:input.linkedin===undefined?(current?.linkedin??null):(String(input.linkedin??'').trim()||null),youtube:input.youtube===undefined?(current?.youtube??null):(String(input.youtube??'').trim()||null),whatsapp:input.whatsapp===undefined?(current?.whatsapp??null):(String(input.whatsapp??'').trim()||null)};if(!data.phone||!data.email||!data.location)throw new Error('Phone, email and location are required.');const saved=await this.prisma.siteSettings.update({where:{id:1},data});const verified=await this.prisma.siteSettings.findUniqueOrThrow({where:{id:1}});if(verified.phone!==data.phone||verified.email!==data.email||verified.location!==data.location||verified.secondaryPhone!==data.secondaryPhone||verified.facebook!==data.facebook||verified.instagram!==data.instagram||verified.x!==data.x||verified.linkedin!==data.linkedin||verified.youtube!==data.youtube||verified.whatsapp!==data.whatsapp){throw new Error("Contact details were not persisted to the database.");}return verified}
@Mutation(()=>DonationMethod)@UseGuards(GqlAuthGuard)updateDonationMethod(@Args('id')id:string,@Args('input')input:DonationMethodInput){try{JSON.parse(input.detailsJson)}catch{throw new Error('Donation details must be valid JSON.')}return this.prisma.donationMethod.update({where:{id},data:input})}
@Mutation(()=>SiteStatistic)@UseGuards(GqlAuthGuard)updateStatistic(@Args('key')key:string,@Args('input')input:SiteStatisticInput){if(!Number.isInteger(input.value)||input.value<0)throw new Error('Statistic value must be a non-negative whole number.');return this.prisma.siteStatistic.update({where:{key},data:input})}
@Mutation(()=>Message)@UseGuards(GqlAuthGuard)updateContactStatus(@Args('id')id:string,@Args('status')status:string){return this.prisma.contactMessage.update({where:{id},data:{status:status as any}})}
@Mutation(()=>Volunteer)@UseGuards(GqlAuthGuard)updateVolunteerStatus(@Args('id')id:string,@Args('status')status:string){if(!['NEW','REVIEWING','APPROVED','DECLINED','REPLIED','ARCHIVED'].includes(status))throw new Error('Invalid volunteer status.');return this.prisma.volunteerApplication.update({where:{id},data:{status:status as any}})}
@Mutation(()=>String)@UseGuards(GqlAuthGuard)async uploadGalleryImage(@Args('filename')filename:string,@Args('contentBase64')contentBase64:string){const token=process.env.GITHUB_TOKEN;const owner=process.env.GITHUB_OWNER||'ssemuyabadev';const repo=process.env.GITHUB_REPO||'sf_frontend';const branch=process.env.GITHUB_BRANCH||'main';const folder=process.env.GITHUB_IMAGES_PATH||'public/images';if(!token)throw new Error('GITHUB_TOKEN is not configured.');const safe=filename.toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/^-+|-+$/g,'');if(!safe)throw new Error('Please provide a valid image filename.');const path=folder.replace(/^\/+|\/+$/g,'')+'/'+Date.now()+'-'+safe;const response=await fetch('https://api.github.com/repos/'+encodeURIComponent(owner)+'/'+encodeURIComponent(repo)+'/contents/'+path,{method:'PUT',headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'},body:JSON.stringify({message:'Add gallery image '+safe,content:contentBase64,branch})});const payload:any=await response.json();if(!response.ok)throw new Error(payload?.message||'GitHub image upload failed.');return GITHUB_IMAGE_BASE+path;}
@Mutation(()=>Gallery)@UseGuards(GqlAuthGuard)createGallery(@Args('input')input:GalleryInput){return this.prisma.galleryItem.create({data:{...input,imageUrl:normalizeImageUrl(input.imageUrl)!}})}
@Mutation(()=>Gallery)@UseGuards(GqlAuthGuard)updateGallery(@Args('id')id:string,@Args('input')input:GalleryInput){return this.prisma.galleryItem.update({where:{id},data:{...input,imageUrl:normalizeImageUrl(input.imageUrl)!}})}
@Mutation(()=>Boolean)@UseGuards(GqlAuthGuard)async deleteGallery(@Args('id')id:string){await this.prisma.galleryItem.delete({where:{id}});return true}
@Mutation(()=>String)@UseGuards(GqlAuthGuard)async uploadNewsImage(@Args('filename')filename:string,@Args('contentBase64')contentBase64:string){const token=process.env.GITHUB_TOKEN;const owner=process.env.GITHUB_OWNER||'ssemuyabadev';const repo=process.env.GITHUB_REPO||'sf_frontend';const branch=process.env.GITHUB_BRANCH||'main';const folder=process.env.GITHUB_IMAGES_PATH||'public/images';if(!token)throw new Error('GITHUB_TOKEN is not configured.');const safe=filename.toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/^-+|-+$/g,'');if(!safe)throw new Error('Please provide a valid image filename.');const path=folder.replace(/^\/+|\/+$/g,'')+'/'+Date.now()+'-'+safe;const response=await fetch('https://api.github.com/repos/'+encodeURIComponent(owner)+'/'+encodeURIComponent(repo)+'/contents/'+path,{method:'PUT',headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'},body:JSON.stringify({message:'Add news image '+safe,content:contentBase64,branch})});const payload:any=await response.json();if(!response.ok)throw new Error(payload?.message||'GitHub image upload failed.');return GITHUB_IMAGE_BASE+path;}
@Mutation(()=>News)@UseGuards(GqlAuthGuard)async createNews(@Args('input')input:NewsInput){return this.prisma.newsPost.create({data:{...input,imageUrl:normalizeImageUrl(input.imageUrl),publishedAt:input.published?new Date():null}})}
@Mutation(()=>News)@UseGuards(GqlAuthGuard)async updateNews(@Args('id')id:string,@Args('input')input:NewsInput){return this.prisma.newsPost.update({where:{id},data:{...input,imageUrl:normalizeImageUrl(input.imageUrl),publishedAt:input.published?new Date():null}})}
@Mutation(()=>Boolean)@UseGuards(GqlAuthGuard)async deleteNews(@Args('id')id:string){await this.prisma.newsPost.delete({where:{id}});return true}}
