import { Args,Field,InputType,Int,Mutation,ObjectType,Query,Resolver } from '@nestjs/graphql';import { UseGuards } from '@nestjs/common';import { PrismaService } from '../prisma.service';import { MailService } from '../mail.service';import { GqlAuthGuard } from '../auth/auth.guard';
const df=()=>Field(()=>Date);
@ObjectType()class Settings{@Field(()=>Int)id!:number;@Field()phone!:string;@Field({nullable:true})secondaryPhone?:string;@Field()email!:string;@Field()location!:string;@Field({nullable:true})facebook?:string;@Field({nullable:true})instagram?:string;@Field({nullable:true})x?:string;@Field({nullable:true})linkedin?:string;@Field({nullable:true})youtube?:string}
@ObjectType()class Message{@Field()id!:string;@Field()name!:string;@Field()email!:string;@Field({nullable:true})phone?:string;@Field({nullable:true})subject?:string;@Field()message!:string;@Field()status!:string;df()createdAt!:Date;df()updatedAt!:Date}
@ObjectType()class Subscriber{@Field()id!:string;@Field()email!:string;df()createdAt!:Date}
@ObjectType()class Volunteer{@Field()id!:string;@Field()name!:string;@Field()email!:string;@Field()phone!:string;@Field()interest!:string;@Field({nullable:true})availability?:string;@Field({nullable:true})message?:string;@Field()status!:string;df()createdAt!:Date;df()updatedAt!:Date}
@ObjectType()class Sponsor{@Field()id!:string;@Field()fullName!:string;@Field()email!:string;@Field()phone!:string;@Field({nullable:true})country?:string;@Field({nullable:true})city?:string;@Field({nullable:true})preferredContact?:string;@Field({nullable:true})sponsorshipPreference?:string;@Field({nullable:true})message?:string;@Field()consent!:boolean;df()createdAt!:Date;df()updatedAt!:Date}
@ObjectType()class Gallery{@Field()id!:string;@Field()title!:string;@Field()imageUrl!:string;@Field({nullable:true})description?:string;@Field({nullable:true})category?:string;@Field()published!:boolean;df()createdAt!:Date;df()updatedAt!:Date}
@ObjectType()class News{@Field()id!:string;@Field()title!:string;@Field()slug!:string;@Field({nullable:true})excerpt?:string;@Field()body!:string;@Field({nullable:true})imageUrl?:string;@Field()published!:boolean;@Field(()=>Date,{nullable:true})publishedAt?:Date;df()createdAt!:Date;df()updatedAt!:Date}
@ObjectType()class Stats{@Field(()=>Int)messages!:number;@Field(()=>Int)newsletter!:number;@Field(()=>Int)volunteers!:number;@Field(()=>Int)sponsors!:number;@Field(()=>Int)gallery!:number;@Field(()=>Int)news!:number}
@InputType()class SettingsInput{@Field()phone!:string;@Field({nullable:true})secondaryPhone?:string;@Field()email!:string;@Field()location!:string;@Field({nullable:true})facebook?:string;@Field({nullable:true})instagram?:string;@Field({nullable:true})x?:string;@Field({nullable:true})linkedin?:string;@Field({nullable:true})youtube?:string}
@InputType()class ContactInput{@Field()name!:string;@Field()email!:string;@Field({nullable:true})phone?:string;@Field({nullable:true})subject?:string;@Field()message!:string}
@InputType()class VolunteerInput{@Field()name!:string;@Field()email!:string;@Field()phone!:string;@Field()interest!:string;@Field({nullable:true})availability?:string;@Field({nullable:true})message?:string}
@InputType()class SponsorInput{@Field()fullName!:string;@Field()email!:string;@Field()phone!:string;@Field({nullable:true})country?:string;@Field({nullable:true})city?:string;@Field({nullable:true})preferredContact?:string;@Field({nullable:true})sponsorshipPreference?:string;@Field({nullable:true})message?:string;@Field()consent!:boolean}
@InputType()class GalleryInput{@Field()title!:string;@Field()imageUrl!:string;@Field()description?:string;@Field()category?:string;@Field({defaultValue:true})published!:boolean}
@InputType()class NewsInput{@Field()title!:string;@Field()slug!:string;@Field({nullable:true})excerpt?:string;@Field()body!:string;@Field({nullable:true})imageUrl?:string;@Field({defaultValue:false})published!:boolean}
@Resolver()export class ContentResolver{constructor(private prisma:PrismaService,private mail:MailService){}
@Query(()=>Settings)siteSettings(){return this.prisma.siteSettings.findUniqueOrThrow({where:{id:1}})}
@Query(()=>[Gallery])gallery(@Args('publishedOnly',{nullable:true,defaultValue:true})publishedOnly:boolean){return this.prisma.galleryItem.findMany({where:publishedOnly?{published:true}:undefined,orderBy:{createdAt:'desc'}})}
@Query(()=>[News])news(@Args('publishedOnly',{nullable:true,defaultValue:true})publishedOnly:boolean){return this.prisma.newsPost.findMany({where:publishedOnly?{published:true}:undefined,orderBy:{publishedAt:'desc'}})}
@Query(()=>News,{nullable:true})newsBySlug(@Args('slug')slug:string){return this.prisma.newsPost.findUnique({where:{slug}})}
@Mutation(()=>Message)async submitContact(@Args('input')input:ContactInput){const saved=await this.prisma.contactMessage.create({data:input});await this.mail.notify('New contact message from '+input.name,'<h2>New contact enquiry</h2><p><b>'+input.name+'</b> ('+input.email+')</p><p>'+input.message+'</p>');return saved}
@Mutation(()=>Subscriber)async subscribeNewsletter(@Args('email')email:string){const saved=await this.prisma.newsletterSubscriber.upsert({where:{email:email.toLowerCase()},update:{},create:{email:email.toLowerCase()}});await this.mail.notify('New newsletter subscriber: '+email,'<p>'+email+' subscribed to the foundation newsletter.</p>');return saved}
@Mutation(()=>Volunteer)async submitVolunteer(@Args('input')input:VolunteerInput){const saved=await this.prisma.volunteerApplication.create({data:input});await this.mail.notify('New volunteer application from '+input.name,'<h2>New volunteer application</h2><p>'+input.name+' — '+input.email+' — '+input.phone+'</p><p>'+input.interest+'</p>');return saved}
@Mutation(()=>Sponsor)async submitSponsor(@Args('input')input:SponsorInput){if(!input.consent)throw new Error('Consent is required.');const saved=await this.prisma.sponsorEnquiry.create({data:input});await this.mail.notify('New sponsorship enquiry from '+input.fullName,'<h2>New sponsorship enquiry</h2><p>'+input.fullName+' — '+input.email+' — '+input.phone+'</p><p>'+(input.sponsorshipPreference??'')+'</p><p>'+(input.message??'')+'</p>');return saved}
@Query(()=>Stats)@UseGuards(GqlAuthGuard)async dashboardStats(){const [messages,newsletter,volunteers,sponsors,gallery,news]=await Promise.all([this.prisma.contactMessage.count(),this.prisma.newsletterSubscriber.count(),this.prisma.volunteerApplication.count(),this.prisma.sponsorEnquiry.count(),this.prisma.galleryItem.count(),this.prisma.newsPost.count()]);return{messages,newsletter,volunteers,sponsors,gallery,news}}
@Query(()=>[Message])@UseGuards(GqlAuthGuard)contactMessages(){return this.prisma.contactMessage.findMany({orderBy:{createdAt:'desc'}})}
@Query(()=>[Subscriber])@UseGuards(GqlAuthGuard)newsletterSubscribers(){return this.prisma.newsletterSubscriber.findMany({orderBy:{createdAt:'desc'}})}
@Query(()=>[Volunteer])@UseGuards(GqlAuthGuard)volunteerApplications(){return this.prisma.volunteerApplication.findMany({orderBy:{createdAt:'desc'}})}
@Query(()=>[Sponsor])@UseGuards(GqlAuthGuard)sponsorEnquiries(){return this.prisma.sponsorEnquiry.findMany({orderBy:{createdAt:'desc'}})}
@Query(()=>[Gallery])@UseGuards(GqlAuthGuard)adminGallery(){return this.prisma.galleryItem.findMany({orderBy:{createdAt:'desc'}})}
@Query(()=>[News])@UseGuards(GqlAuthGuard)adminNews(){return this.prisma.newsPost.findMany({orderBy:{createdAt:'desc'}})}
@Mutation(()=>Settings)@UseGuards(GqlAuthGuard)updateSiteSettings(@Args('input')input:SettingsInput){return this.prisma.siteSettings.upsert({where:{id:1},update:input,create:{id:1,...input}})}
@Mutation(()=>Message)@UseGuards(GqlAuthGuard)updateContactStatus(@Args('id')id:string,@Args('status')status:string){return this.prisma.contactMessage.update({where:{id},data:{status:status as any}})}
@Mutation(()=>Volunteer)@UseGuards(GqlAuthGuard)updateVolunteerStatus(@Args('id')id:string,@Args('status')status:string){return this.prisma.volunteerApplication.update({where:{id},data:{status:status as any}})}
@Mutation(()=>Gallery)@UseGuards(GqlAuthGuard)createGallery(@Args('input')input:GalleryInput){return this.prisma.galleryItem.create({data:input})}
@Mutation(()=>Gallery)@UseGuards(GqlAuthGuard)updateGallery(@Args('id')id:string,@Args('input')input:GalleryInput){return this.prisma.galleryItem.update({where:{id},data:input})}
@Mutation(()=>Boolean)@UseGuards(GqlAuthGuard)async deleteGallery(@Args('id')id:string){await this.prisma.galleryItem.delete({where:{id}});return true}
@Mutation(()=>News)@UseGuards(GqlAuthGuard)async createNews(@Args('input')input:NewsInput){return this.prisma.newsPost.create({data:{...input,publishedAt:input.published?new Date():null}})}
@Mutation(()=>News)@UseGuards(GqlAuthGuard)async updateNews(@Args('id')id:string,@Args('input')input:NewsInput){return this.prisma.newsPost.update({where:{id},data:{...input,publishedAt:input.published?new Date():null}})}
@Mutation(()=>Boolean)@UseGuards(GqlAuthGuard)async deleteNews(@Args('id')id:string){await this.prisma.newsPost.delete({where:{id}});return true}}
